spring:
  datasource:
    url: jdbc:h2:file:/data/casadocodigo;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driverClassName: org.h2.Driver
    initialization-mode: always
    sql-script-encoding: UTF-8
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2


